import 'package:flutter/widgets.dart';
import 'outlined.dart';
import 'variant.dart';
import 'styler.dart';

/// A powerful widget that builds upon
/// the familiar Flutter Text widget,
/// offering additional functionalities
/// for a richer text display experience.
class WxText extends OutlinedText {
  /// Create an extended text widget
  const WxText(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
    this.variant,
  });

  /// Create an extended text widget from other instance
  WxText.from(
    WxText other, {
    super.key,
    String? text,
  })  : variant = other.variant,
        super(
          text ?? other.text,
          style: other.style,
          strutStyle: other.strutStyle,
          textAlign: other.textAlign,
          textDirection: other.textDirection,
          textScaler: other.textScaler,
          locale: other.locale,
          softWrap: other.softWrap,
          overflow: other.overflow,
          maxLines: other.maxLines,
          minLines: other.minLines,
          semanticsLabel: other.semanticsLabel,
          textWidthBasis: other.textWidthBasis,
          textHeightBehavior: other.textHeightBehavior,
          highlight: other.highlight,
          highlightStyle: other.highlightStyle,
          highlightOnTap: other.highlightOnTap,
          filter: other.filter,
          filterDisabled: other.filterDisabled,
          filterCaseSensitive: other.caseSensitive,
          filterMultiLine: other.multiLine,
          filterUnicode: other.unicode,
          filterDotAll: other.dotAll,
          borderColor: other.borderColor,
          borderWidth: other.borderWidth,
          gradient: other.gradient,
        );

  /// Create a large display text widget
  const WxText.displayLarge(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.displayLarge;

  /// Create a medium display text widget
  const WxText.displayMedium(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.displayMedium;

  /// Create a small display text widget
  const WxText.displaySmall(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.displaySmall;

  /// Create a large headline text widget
  const WxText.headlineLarge(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.headlineLarge;

  /// Create a medium headline text widget
  const WxText.headlineMedium(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.headlineMedium;

  /// Create a small headline text widget
  const WxText.headlineSmall(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.headlineSmall;

  /// Create a large body text widget
  const WxText.bodyLarge(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.bodyLarge;

  /// Create a medium body text widget
  const WxText.bodyMedium(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.bodyMedium;

  /// Create a small body text widget
  const WxText.bodySmall(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.bodySmall;

  /// Create a large label text widget
  const WxText.labelLarge(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.labelLarge;

  /// Create a medium label text widget
  const WxText.labelMedium(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.labelMedium;

  /// Create a small label text widget
  const WxText.labelSmall(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.labelSmall;

  /// Create a large title text widget
  const WxText.titleLarge(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.titleLarge;

  /// Create a medium title text widget
  const WxText.titleMedium(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.titleMedium;

  /// Create a small title text widget
  const WxText.titleSmall(
    super.text, {
    super.key,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textScaler,
    super.locale,
    super.softWrap,
    super.overflow,
    super.maxLines,
    super.minLines,
    super.semanticsLabel,
    super.textWidthBasis,
    super.textHeightBehavior,
    super.highlight,
    super.highlightStyle,
    super.highlightOnTap,
    super.filter,
    super.filterDisabled,
    super.filterCaseSensitive,
    super.filterMultiLine,
    super.filterUnicode,
    super.filterDotAll,
    super.borderColor,
    super.borderWidth,
    super.gradient,
  }) : variant = WxTextVariant.titleSmall;

  /// The variant text style to apply.
  final WxTextVariantBuilder? variant;

  @override
  Widget build(BuildContext context) {
    return WxTextStyler(
      style: style,
      variant: variant,
      child: Builder(builder: (context) {
        return super.build(context);
      }),
    );
  }
}
